CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNOS(
MATRICULA INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SEXO CHAR(1) NOT NULL,
CONSTRAINT PK_MATRICULA_ALUNO PRIMARY KEY(MATRICULA)
);

CREATE TABLE DISCIPLINAS(
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  CONSTRAINT PK_ID_DISCIPLINA PRIMARY KEY(ID)
 );

 CREATE TABLE PROFESSOR(
 	ID INT NOT NULL AUTO_INCREMENT,
 	NOME VARCHAR(50) NOT NULL,
   	SEXO CHAR(1) NOT NULL,
   CONSTRAINT PK_ID_PROFESSOR PRIMARY KEY(ID)
 );

USE ESCOLA;
 CREATE TABLE TURMA(
   ID INT NOT NULL AUTO_INCREMENT,
   PROFESSORID INT NOT NULL,
   DISCIPLINAID INT NOT NULL,
   SEMESTRE INT NOT NULL,
   ANO INT NOT NULL,

   CONSTRAINT PK_ID_TURMA PRIMARY KEY (ID),
   CONSTRAINT FK_PROFESSORID FOREIGN KEY (PROFESSORID) REFERENCES PROFESSOR(ID),
   CONSTRAINT FK_DISCIPLINAID FOREIGN KEY (DISCIPLINAID) REFERENCES DISCIPLINAS(ID)
 );sele
